site_name: MagnetoPy
site_description: Magnetometry Research in Python
site_author: Rinehart Group
nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorial: tutorial.md
  - Examples: examples.md
  - File Formatting: parsing_guidelines.md
  - API:
      - Magnetopy:
          - Magnetometry: api/magnetometry.md
          - Data Files:
              - DatFile: api/dat_file.md
              - GenericFile: api/generic_file.md
          - Experiments:
              - DcExperiment: api/dc_experiment.md
              - MvsH: api/mvsh.md
              - ZFC, FC, ZFCFC: api/zfcfc.md
              - Utils: api/experiments_utils.md
          - Utils:
              - Parsing: api/parsing_utils.md
              - Plotting: api/plot_utils.md
  - About: about.md

theme:
  name: material
  logo: assets/icons/72ppi/magpy_72ppi.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.next_prev
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_root_heading: true
            members_order: source
            docstring_style: numpy
watch:
  - docs
  - magnetopy
markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  #   - admonition
  #   - footnotes
  #   - pymdownx.details
  #   - pymdownx.superfences
  #   - pymdownx.mark
  - attr_list
